Update patch set 3
Patch Set 3:

Breaks my build:

 CC      block/fiops-iosched.o
../../../../../../kernel/samsung/trlte/block/fiops-iosched.c: In function 'fiops_init_prio_data':
../../../../../../kernel/samsung/trlte/block/fiops-iosched.c:470:3: error: implicit declaration of function 'task_ioprio' [-Werror=implicit-function-declaration]
   cic->ioprio = task_ioprio(ioc);
   ^
../../../../../../kernel/samsung/trlte/block/fiops-iosched.c: At top level:
../../../../../../kernel/samsung/trlte/block/fiops-iosched.c:728:3: warning: initialization from incompatible pointer type [enabled by default]
error, forbidden warning: fiops-iosched.c:728

Patch-set: 3
Reviewer: Allard addink <11448@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0